

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - chroma
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDBE: ${MONGO_URI}
     
     
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

volumes:
  mongo_data:
  chroma_data:
